/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as IndexImport } from './routes/index'
import { Route as StarIndexImport } from './routes/star/index'
import { Route as EditorIndexImport } from './routes/editor/index'
import { Route as VideoSearchImport } from './routes/video/search'
import { Route as VideoAddImport } from './routes/video/add'
import { Route as VideoVideoIdImport } from './routes/video/$videoId'
import { Route as StarSearchImport } from './routes/star/search'
import { Route as StarStarIdImport } from './routes/star/$starId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StarIndexRoute = StarIndexImport.update({
  path: '/star/',
  getParentRoute: () => rootRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

const VideoSearchRoute = VideoSearchImport.update({
  path: '/video/search',
  getParentRoute: () => rootRoute,
} as any)

const VideoAddRoute = VideoAddImport.update({
  path: '/video/add',
  getParentRoute: () => rootRoute,
} as any)

const VideoVideoIdRoute = VideoVideoIdImport.update({
  path: '/video/$videoId',
  getParentRoute: () => rootRoute,
} as any)

const StarSearchRoute = StarSearchImport.update({
  path: '/star/search',
  getParentRoute: () => rootRoute,
} as any)

const StarStarIdRoute = StarStarIdImport.update({
  path: '/star/$starId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/star/$starId': {
      preLoaderRoute: typeof StarStarIdImport
      parentRoute: typeof rootRoute
    }
    '/star/search': {
      preLoaderRoute: typeof StarSearchImport
      parentRoute: typeof rootRoute
    }
    '/video/$videoId': {
      preLoaderRoute: typeof VideoVideoIdImport
      parentRoute: typeof rootRoute
    }
    '/video/add': {
      preLoaderRoute: typeof VideoAddImport
      parentRoute: typeof rootRoute
    }
    '/video/search': {
      preLoaderRoute: typeof VideoSearchImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
    '/star/': {
      preLoaderRoute: typeof StarIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SettingsRoute,
  StarStarIdRoute,
  StarSearchRoute,
  VideoVideoIdRoute,
  VideoAddRoute,
  VideoSearchRoute,
  EditorIndexRoute,
  StarIndexRoute,
])

/* prettier-ignore-end */
